uploads = []
outputs = []

[[generated]]
id = "areYb4cl1sAbYuAdUdxo4"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "SurBGrZEAUzqbvzKRoSZO"
uri = "file://artifacts/mobile/assets/images/splash.png"
type = "image"
title = "generated_image"
